services:


  discord-bot:
    build:
      context: ./discord-bot
      dockerfile: ./bot.dockerfile
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    env_file:
      - ./discord-bot/dev.env

  profile-broker:
    build:
      context: ./profile-broker
      dockerfile: ./broker.dockerfile
    restart: always

    deploy:
      mode: replicated
      replicas: 1
  http-broker:
    build:
      context: ./http-broker
      dockerfile: ./http-broker.dockerfile
    restart: always
    ports:
      - "4455:4455"

    deploy:
      mode: replicated
      replicas: 1

  auth-service:
    build:
      context: ./auth-service
      dockerfile: ./auth.dockerfile
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    env_file:
      - ./auth-service/dev.env
      - ./secrets.env

  postgres:
    image: 'postgres:14.2'
    ports:
      - "5432:5432"
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    env_file:
      - ./db.dev.env
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data/
